apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
spec:
  replicas: 1
  selector:
    app: webserver-app
  template:
    metadata:
      name: webserver-pod
      labels:
        app: webserver-app
    spec:
      containers:
      - name: nginx
        image: michiel:nginx
        ports:
        - containerPort: 80
